openapi: 3.0.3
info:
  description: Plex OpenAPI Spec
  title: Plex
  version: 1.0.0
paths:
  /invite/send:
    post:
      description: This endpoint sends an invite to a user to join a tenant
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlexSendInviteRequest'
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: Send Invite
      tags:
      - Invites
  /loginapp/register:
    get:
      description: This endpoint lists all login applications for the tenant. Only
        tenant admins can list login applications.
      parameters:
      - description: Optional organization ID filter
        in: query
        name: organization_id
        schema:
          description: Optional organization ID filter
          nullable: true
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/PlexLoginAppResponse'
                type: array
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: List Login Applications
      tags:
      - Login Application
    post:
      description: This endpoint creates a new login application for the tenant. Only
        tenant admins can create login applications.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlexLoginAppRequest'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlexLoginAppResponse'
          description: Created
        "500":
          description: Internal Server Error
      summary: Create Login Application
      tags:
      - Login Application
  /loginapp/register/{id}:
    delete:
      description: This endpoint deletes a login application for the tenant. Only
        tenant admins can delete login applications.
      parameters:
      - in: path
        name: id
        required: true
        schema:
          $ref: '#/components/schemas/UuidUUID'
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
      summary: Delete Login Application
      tags:
      - Login Application
    get:
      description: This endpoint retrieves a login application for the tenant. Only
        tenant admins can get login applications.
      parameters:
      - in: path
        name: id
        required: true
        schema:
          $ref: '#/components/schemas/UuidUUID'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlexLoginAppResponse'
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get Login Application
      tags:
      - Login Application
    put:
      description: This endpoint updates a login application for the tenant. Only
        tenant admins can update login applications.
      parameters:
      - in: path
        name: id
        required: true
        schema:
          $ref: '#/components/schemas/UuidUUID'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginappLoginAppRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlexLoginAppResponse'
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Update Login Application
      tags:
      - Login Application
components:
  schemas:
    LoginappLoginAppRequest:
      properties:
        client_name:
          type: string
        client_uri:
          type: string
        contacts:
          items:
            type: string
          type: array
        grant_types:
          items:
            type: string
          type: array
        jwks:
          type: string
        jwks_uri:
          type: string
        logo_uri:
          type: string
        policy_uri:
          type: string
        redirect_uris:
          items:
            type: string
          type: array
        response_types:
          items:
            type: string
          type: array
        scope:
          type: string
        software_id:
          type: string
        software_statement:
          type: string
        software_version:
          type: string
        token_endpoint_auth_method:
          type: string
        tos_uri:
          type: string
      type: object
    PlexLoginAppRequest:
      properties:
        client_name:
          type: string
        client_uri:
          type: string
        contacts:
          items:
            type: string
          type: array
        grant_types:
          items:
            type: string
          type: array
        jwks:
          type: string
        jwks_uri:
          type: string
        logo_uri:
          type: string
        policy_uri:
          type: string
        redirect_uris:
          items:
            type: string
          type: array
        response_types:
          items:
            type: string
          type: array
        scope:
          type: string
        software_id:
          type: string
        software_statement:
          type: string
        software_version:
          type: string
        token_endpoint_auth_method:
          type: string
        tos_uri:
          type: string
      type: object
    PlexLoginAppResponse:
      properties:
        Metadata:
          $ref: '#/components/schemas/PlexLoginAppRequest'
        app_id:
          $ref: '#/components/schemas/UuidUUID'
        client_id:
          type: string
        client_id_issued_at:
          format: date-time
          type: string
        client_secret:
          type: string
        client_secret_expires_at:
          format: date-time
          type: string
        organization_id:
          $ref: '#/components/schemas/UuidUUID'
      type: object
    PlexSendInviteRequest:
      properties:
        client_id:
          type: string
        expires:
          format: date-time
          type: string
        invite_text:
          type: string
        invitee_email:
          type: string
        inviter_email:
          type: string
        inviter_name:
          type: string
        inviter_user_id:
          type: string
        redirect_url:
          type: string
        state:
          type: string
      type: object
    UuidUUID:
      example: 248df4b7-aa70-47b8-a036-33ac447e668d
      format: uuid
      type: string
servers:
- url: https://your-tenant-name.tenant.userclouds.com
x-readme:
  explorer-enabled: false
